### ISSUE TITLE
[Bug Report] レイヤーから削除したあと操作するとエラーが生まれる

### ISSUE THREAD

**Issue by K-Kazuyuki** [tsukuba-cojt/resta#143]

**Comment by itsu-dev** [comment]
たとえば、スタイルAを適用してレイヤタブでAの削除をし、その後Aを再度適用しようとするとエラーが発生する。
以下はエラー内容：
```
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at main.js:2:505042
    at D (main.js:2:505386)
    at r (main.js:2:1165096)
    at onChange (main.js:2:900154)
    at he (main.js:2:886560)
    at Z (main.js:2:887670)
    at Object.P (main.js:2:887913)
    at HTMLDocument.u (main.js:2:888486)
```
  
以下はmain.js:2:505042周辺のコード（`t.commands[0].id` でエラー発生）：
```
n.commands.length > 0 && function(e) {
                if (0 !== e.commands.length) {
                    M < P.length && P.splice(M, P.length - M);
                    var t = P[P.length - 1];
                    t && 0 !== t.commands[0].id && t.commands[0].id === e.commands[0].id && "delete" !== t.commands[0].redo.type && "delete" !== e.commands[0].redo.type && t.commands.map((function(e) {
                        return e.cssSelector
                    }
                    )).sort().toString() === e.commands.map((function(e) {
                        return e.cssSelector
                    }
                    )).sort().toString() ? (P.pop(),
                    P.push(I(t, e))) : P.push(e),
                    P.length > 32 && P.shift(),
                    M = P.length,
                    s("pushLog", P),
                    S()
                }
            }(n)
```

**Comment by itsu-dev** [comment]
@K-Kazuyuki

**Comment by K-Kazuyuki** [comment]
修正しました
